version: '3.8'

services:
  epic-team-app:
    build: ./
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=12345
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=12345
    ports:
      - 5436:5432
