"""empty message

Revision ID: 238e653bc098
Revises: b2ddb0764945
Create Date: 2021-10-16 17:55:56.344215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238e653bc098'
down_revision = 'b2ddb0764945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameaccount', sa.Column('email', sa.String(length=60), nullable=False))
    op.add_column('gameaccount', sa.Column('password', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gameaccount', 'password')
    op.drop_column('gameaccount', 'email')
    # ### end Alembic commands ###
