"""empty message

Revision ID: e33cb3bfd6f9
Revises: 238e653bc098
Create Date: 2021-10-16 17:57:49.578556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33cb3bfd6f9'
down_revision = '238e653bc098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameaccount', sa.Column('email', sa.String(length=60), nullable=False))
    op.add_column('gameaccount', sa.Column('password', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gameaccount', 'password')
    op.drop_column('gameaccount', 'email')
    # ### end Alembic commands ###
