"""empty message

Revision ID: ebec2bcbbbf1
Revises: 501a557846f0
Create Date: 2021-10-16 17:58:31.009610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebec2bcbbbf1'
down_revision = '501a557846f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameaccount', sa.Column('email', sa.String(length=60), nullable=True))
    op.add_column('gameaccount', sa.Column('password', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gameaccount', 'password')
    op.drop_column('gameaccount', 'email')
    # ### end Alembic commands ###
